mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: >
   cn.dylan0011.utils.(test1|test2).model,
   io.terminus.nidoking.item.model

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ec?useUnicode=true&characterEncoding=UTF8
    username: root
    password: anywhere